DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    voornaam VARCHAR (50) NOT NULL,
    familienaam VARCHAR (50) NOT NULL,
    klas VARCHAR (10) NOT NULL, PRIMARY KEY (id)
)